### PR TITLE
CPN Improve layout - fix 2036733

### PR DESCRIPTION
**Pull request by mtygesen**
Fixes this:
https://bugs.launchpad.net/tapaal/+bug/2036733

### CODE REVIEW

**Review by yrke — APPROVED** [review]

**Review by srba — CHANGES_REQUESTED** [review]
Works very well - but if I make very long color type (e.g. many colors or long color names) and then make variable of that color type, the dialog will get out of screen - it should have some fixed width and perhaps use the ... notation if the colortype to select from is too long.

**Comment by mtygesen** [comment]
+ Fixed width of edit color type window and edit variable for very long names
+ Added ellipsis for edit variable window
+ Added fallback to enter component name and edit shared place in case operating system allows window to still be resized even after setResize(false)

**Review by srba — CHANGES_REQUESTED** [review]
On mac the first time I click on "New compoment" gives a dialog that is minimized to 1x2 cm. Second time I click on it it looks fine.

**Comment by srba** [comment]
The "New component" dialog on mac now does not have the double border, but the "Edit color type" and "Create variable" dialogs still have a double bound.

**Comment by srba** [comment]
"Edit arc" and "Edit transitions" also have double bounds.

**Review by srba — APPROVED** [review]
All looks good. Merging to main now.

**Pull request merged**
