### PR TITLE
Premature end of file in CPN verifypn - fix 2046960

### PR DESCRIPTION
**Pull request by mtygesen**
Fixes:
https://bugs.launchpad.net/tapaal/+bug/2046960

### CODE REVIEW

**Review by srba — CHANGES_REQUESTED** [review]
I cannot see what issues this fixes? How to reproduce a bug that this PR should fix?

If I open the query, select "some trace" and then use raw option "-x 1" it still gives an error that the PNML file cannot be read.

**Review by srba — CHANGES_REQUESTED** [review]
Does not solve the problem.
Open the query, deselect "Use net reduction" (the button gets disabled).
Now click on "Use" raw options and deselect the "Use" again.
Now the "Use net reductions" is not enabled but I can open the reduced net as the button is enabled (and this gives the error).

Also, if you select "some trace" and then click on "Use" with "-x 1" as the only option, this gives an error with reading the PNML file as well (there is no trace in the output but the GUI expects the output).

**Review by srba — CHANGES_REQUESTED** [review]
Does not solve the problem with traces.

Open the colored referendum CPN.
Select "some trace".
Select "Use"
Run the verification and you get a problem with parsing PNML file.

**Comment by mtygesen** [comment]
Merging together with other pr

**Pull request closed without merging**
