### PR TITLE
Fixes to HyperLTL query dialog

### PR DESCRIPTION
**Pull request by srba**
Fixes several issues with HyperLTL dialog, in particular the bug
https://bugs.launchpad.net/tapaal/+bug/2035183 of NPE when trace edit dialog was cancelled

### CODE REVIEW

**Comment by Malleek** [comment]
Fixes the NPE problem and the escape/close popup issue too.
I still see 2 things:
- New query -> HyperLTL -> Edit Trace -> click on T1 -> OK -> Edit trace -> T1 is still selected and the buttons up and down are enabled (only the down button should be enabled, or T1 should not be selected)
- New query -> HyperLTL -> Edit Trace -> add trace (give it a name first) -> nothing is selected, but Remove button is enabled. Gives a NPE line 3534 of QueryDialog (just add `[...] != null &&` would probably be good) if Remove is pressed

**Comment by srba** [comment]
I have now addressed the two issues above. @Malleek, can you test it one more time please?

**Comment by Malleek** [comment]
Now the up and down buttons are enabled when entering Edit Traces for the first time (or after closing it without selected any trace). 
And there is an Array out of bound error in `initTraceBoxDialogComponents`

**Comment by srba** [comment]
I fixed the buttons up/down. How can I reproduce the out of bounds error?

**Comment by Malleek** [comment]
Now the up and down buttons are enabled when entering Edit Traces for the first time (or after closing it without selected any trace). Clicking on these buttons triggers an Array out of bound error in `initTraceBoxDialogComponents`

**Comment by Malleek** [comment]
Clicking on the enabled buttons actually triggered the error, but now it is fine.
I see no more issue.

**Review by Malleek — APPROVED** [review]

**Pull request merged**
