### PR TITLE
Colored structural reduction 1987636

### PR DESCRIPTION
**Pull request by LenaSaid**
Added colored structural reduction option to the advanced options for colored, non-game, untimed nets.

Solves https://bugs.launchpad.net/tapaal/+bug/1987636.

### CODE REVIEW

**Review by srba — CHANGES_REQUESTED** [review]
Please, enable the colored structural reductions be default.

Please, swap the siphon-trap with the colored reductions.

If the net is "game" the colored reductions should be grayed out (as the normal reductions are too).

Please, rename "Apply net reductions" -> "Use net reductions"
and write "Use colored net reductions" for the newly added feature.

**Comment by LenaSaid** [comment]
> Please, enable the colored structural reductions be default.
> 
> Please, swap the siphon-trap with the colored reductions.
> 
> If the net is "game" the colored reductions should be grayed out (as the normal reductions are too).
> 
> Please, rename "Apply net reductions" -> "Use net reductions" and write "Use colored net reductions" for the newly added feature.

Should be fixed now

**Review by srba — COMMENTED** [review]
Tested and works fine but please disable trace abstraction refinement in case the net is a game.

**Comment by LenaSaid** [comment]
> Tested and works fine but please disable trace abstraction refinement in case the net is a game.

Should be disabled now

**Pull request merged**
